# site configuration

theme: jekyll-theme-chirpy

lang: en

# https://kevinnovak.github.io/Time-Zone-Picker
timezone: America/New_York

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md

# main title
title: Corey Goldberg

# subtitle
tagline: Team 457

# used by seo meta and the atom feed
description: Grease Monkeys

# protocol & hostname for your site (it does not end with a '/')
url: https://frc457.github.io

author:
  name: Team 457
  # sets the `author.url` property. helps Google to disambiguate the correct author of articles
  #url: https://github.com/cgoldberg

# URL to a site-wide logo (e.g.: /assets/your-company-logo.png)
#logo:

github:
  username: frc457

#twitter:
#  username: cgoldberg

social:
  # displayed as the default author of the posts and the copyright owner in the footer
  name: Team 457
  #email: example@domain.com
  links:
    # first element serves as the copyright owner's link
    - https://github.com/frc457
    - https://instagram.com/frc457
    # uncomment below to add more social links
    # - https://www.facebook.com/username
    # - https://twitter.com/username
